apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: taskflow
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: taskflow.local
      http:
        paths:
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: taskflow-worker
                port:
                  number: 8001
          - path: /api/analytics
            pathType: Prefix
            backend:
              service:
                name: taskflow-worker
                port:
                  number: 8001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskflow-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-frontend
                port:
                  number: 80
